# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mix_ll <- function(theta, Y, X, d, latent, family, isLog, constraint) {
    .Call('_fmmr6_mix_ll', PACKAGE = 'fmmr6', theta, Y, X, d, latent, family, isLog, constraint)
}

post_pr <- function(theta, pi_v, Y, X, latent, family, constraint) {
    .Call('_fmmr6_post_pr', PACKAGE = 'fmmr6', theta, pi_v, Y, X, latent, family, constraint)
}

